stages:
  - deploy

before_script:
  - type trdl && . $(trdl use werf 1.2 ea)
  - type werf && source $(werf ci-env gitlab --as-file)

.base_deploy:
  stage: deploy
  script:
    - werf converge
      --set "global.ci_registry=$CI_REGISTRY"
      --set "global.ci_registry_username=$CI_DEPLOY_USER"
      --set "global.ci_registry_password=$CI_DEPLOY_PASSWORD"
      --set "global.ci_environment_url=$(cut -d / -f 3 <<< $CI_ENVIRONMENT_URL)"
  tags:
    - shell
  except:
    - schedules
  when: manual

Production:
  extends:
    - .base_deploy
  environment:
    name: production
    url: https://crossings.eraelec.ru
  only:
    - master
    - branches
  when: on_success
