apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-cron
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-cron
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/php-config: {{ include (print $.Template.BasePath "/10-php-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}-cron
    spec:
      imagePullSecrets:
        - name: {{ .Chart.Name }}-registrysecret
      terminationGracePeriodSeconds: 120
      volumes:
        - name: php-config
          configMap:
            name: php-config
      containers:
        - name: cron
          image: {{ .Values.werf.image.backend }}
          command: ["/usr/local/bin/dumb-init", "--rewrite", "3:15", "--"]
          args:
            - '/usr/local/bin/supercronic'
            - '-prometheus-listen-address=:9101'
            - '/app/{{ .Values.schedule._default }}'
          volumeMounts:
            - name: php-config
              mountPath: /usr/local/etc/php/conf.custom/app-custom.ini
              subPath: app-custom.ini
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
              subPath: docker-php-ext-xdebug.ini
            - name: php-config
              mountPath: /usr/local/etc/php-fpm.d/zzz-php-fpm-config.conf
              subPath: zzz-php-fpm-config.conf
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/tzone.ini
              subPath: tzone.ini
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
              ephemeral-storage: 200Mi
            limits:
              memory: 512Mi
              ephemeral-storage: 400Mi
          env:
            - name: PHP_INI_SCAN_DIR
              value: :/usr/local/etc/php/conf.custom
{{- include "app_env" . | indent 12 }}
