---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx-prod
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: {{ .Values.global.env_host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Chart.Name }}-app
              servicePort: 80

  tls:
    - hosts:
        - {{ .Values.global.env_host }}
      secretName: {{ .Chart.Name }}-tls
